name: SwiftLint

on:
  pull_request:
  workflow_dispatch:

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run SwiftLint
        run: swiftlint --reporter github-actions-logging
